import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";
import "./globals.css";
import { ModeToggle } from "@/components/ui/theme-toggle";
import FooterColumns01 from "@/components/blocks/footer/footer-columns-01";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const h = await headers();
  const pathname = h.get("x-url") || "";
  const hideNavFooter =
    pathname.includes("/login") || pathname.includes("/signup");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased container max-w-7xl mx-auto p-4`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {!hideNavFooter && <Navbar hideOnTopHome={true} />}
          {children}
          {/* <ModeToggle /> */}
          {!hideNavFooter && <FooterColumns01 />}
        </ThemeProvider>
      </body>
    </html>
  );
}
